monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: group
            members: [file, gelf]
        file:
            type: stream
            path: "php://stderr"
            level: debug
        gelf:
            type: gelf
            publisher:
                hostname: "%env(resolve:LOGSTASH_HOSTNAME)%"
                port: "%env(resolve:LOGSTASH_PORT)%"
            level: debug 
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
