parameters:
    locale: 'en'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Sudoku\:
        resource: '../src/Sudoku/*'

    Sudoku\UI\Controller\:
        resource: '../src/Sudoku/UI/Controller'
        public: true
        tags: ['controller.service_arguments']


    Sudoku\UI\ConsoleCommand\SudokuBackTrackingCommand:
        arguments:
            $boardsDirectory: "%kernel.root_dir%/Sudoku/App/Boards/"
        tags:
            - { name: 'console.command', command: 'sudoku:backtracking:solve' }
